services:
  - type: web
    name: tsm-portfolio
    runtime: python
    buildCommand: ""
    startCommand: gunicorn tsm_portfolio.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tsm_portfolio.settings
      - key: PYTHON_VERSION
        value: 3.11.8
