services:
  - type: web
    name: tsm-portfolio
    runtime: python
    buildCommand: "./build.sh"
    startCommand: gunicorn portfolio_tsm.wsgi:application
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_tsm.settings
      - key: PYTHON_VERSION
        value: 3.11.8
